### ISSUE TITLE
Error locations get skewed in the presence of unicode characters

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#193]
This is likely an upstream bug, but when in the presence of unicode characters, the reported error locations are skewed:
![image](https://user-images.githubusercontent.com/8614547/213308597-733c4c9b-3d66-46b1-8daa-c5d13572bc18.png)

You can try this example for yourself:
```coq
Definition foo : forall Γ Γ' (Γ ⊆ Γ') : Type.
```
It isn't just parser errors, this is just a minimal example.

**Comment by ejgallego** [comment]
Yes, this is a known bug and I was indeed procrastinating on submitting it.

To fix it properly we still need a better separation of language vs server locations, I have a branch for that on my disk.

LSP is a mess w.r.t. to character sets, see for example the discussion here https://github.com/Deducteam/lambdapi/issues/452

**Comment by ejgallego** [comment]
Main difficulty we face is that Fleche must support both line / column and offset based reporting, due to different editors and protocols requiring that, and in particular ProseMirror needs offset.

Offset is kinda tricky but maybe we could declare that our offsets are byte based, it seems Prosemirror follows that model?
