### ISSUE TITLE
Support for Typeclasses Debug

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#308]
Certain commands give the user messages such as `Set Typeclasses Debug` during a typeclass search. The output of this command is currently lost. What would be a sensible way to display such output to the user?

**Comment by ejgallego** [comment]
I guess we can use the messages panel for that?

Maybe we could actually do as your propose and sub-divide the panel in Warnings, Info, Debug.

Ideally we would for typeclasses debug what we have done for obligations and just have a better UI, instead of having the user rely on the clumsy "Show Obligations".
