### ISSUE TITLE
Progress indicator and comments don't interact correctly

### ISSUE THREAD

**Issue by Alizter** [ejgallego/coq-lsp#445]
The following has the "correct" progress indication:
```coq
Comments Here is some vernac.
Comments Here is some vernac.
Comments Here is some vernac.
```
Here is how it is rendered:

![image](https://user-images.githubusercontent.com/8614547/222823648-4cdcc3a1-3891-404b-a3fa-876916f729cb.png)

However adding a new line leaves a trailing "processing" indicator:

![image](https://user-images.githubusercontent.com/8614547/222823773-249c0350-0d63-4d7c-8700-3cef1545e39b.png)

It always appears to be the last 2 lines:
![image](https://user-images.githubusercontent.com/8614547/222823856-f0726f00-6e52-41d1-b7ce-f7fbc61ccbe2.png)

Furthermore, commenting out the end lines will leave the progress indicator there too:

![image](https://user-images.githubusercontent.com/8614547/222823971-a108c159-b4ff-46a1-9017-7001b1ffdcc7.png)

**Comment by ejgallego** [comment]
This is because Coq will actually not process that part of the file, there is already a TODO in `doc.ml`:

```ocaml
    match res with
    | Ok None ->
      (* We actually need to fix Coq to return the location of the true file
         EOF, the below trick doesn't work. That will involved updating the type
         of `main_entry` *)
      let last_tok = Coq.Parsing.Parsable.loc doc_handle in
      let last_tok = Coq.Utils.to_range ~lines last_tok in
      (EOF (Yes last_tok), [], feedback, time)
```

So indeed Coq's parser will just return `None` and give us no info about the rest of the buffer. The best way to fix this would be for the Coq parser to give us the last seen location in the file, that would involve modifying `Pvernac.Vernac_.main_entry` to have a better type:
```ocaml
    val main_entry : vernac_control option Entry.t
```
We could also change our code to infer the last location in the file from `contents`, however I'm a bit way of us doing that, as it would mask any strange stuff coming from Coq.
