### ISSUE TITLE
[coq markdown] Enable Preview Command in Coq Markdown mode

### ISSUE THREAD

**Issue by ejgallego** [ejgallego/coq-lsp#456]
This allows us to view Coq markdown docs with latex in a much better way.

Thanks to Sam van Gool by the suggestion.

**Comment by ejgallego** [comment]
@4ever2 , I'm taking the freedom to ping you with this, as you did the nice work on #307 

Do you know how to make the markdown mode commands available for `.mv` files?

The example we have in a proof we are working is:
```markdown
## Hello
Some math $x_i \star x_j = x_j \star x_i$ 

\```coq
Definition comm (x_i x_j : nat) := x_i + x_j = x_j + x_i.
\```
```

So then you do markdown preview in a different panel and it looks so nice!

**Comment by 4ever2** [comment]
> Do you know how to make the markdown mode commands available for `.mv` files?

I think that is tricky to do. VS Code supports embedded LSP through language services and request forwarding (https://code.visualstudio.com/api/language-extensions/embedded-languages). However, it doesn't seem to suit this use case perfectly.

An alternative solution would be to register `.mv` files as an alias of Markdown rather than its own CoqMarkdown language. Then we can have the language client only start for Markdown files that also have the `.mv` file extension.
I implemented a prototype of that [here](https://github.com/4ever2/coq-lsp/commit/1536c0fbc597dba1648268407ea9b8028d68657c).
It seems to work well, but I haven't tested it thoroughly. So there might be some downsides that I haven't thought of.

On a side note, the "Show Goals at Point" command seems to be broken when using the keybind.
It inserts a new line when used, which is not desirable.

**Comment by ejgallego** [comment]
Thanks a lot for the info @4ever2 , I have tried your prototype and I think I'm gonna add it to 0.1.7 , it seems to me that it makes sense, thanks a lot.

**Comment by ejgallego** [comment]
If you think that we should research more into embedded languages please say so and we can open an issue to track it.
