### ISSUE TITLE
cannot find a physical path

### ISSUE THREAD

**Issue by ASamSam** [ejgallego/coq-lsp#482]
Hello,
i did install coq-lsp for Ubuntu on virtual machine

i have several files, one imports another 
`Require Import BasicFacts.`
But for this line I have an error message:
`Cannot find a physical path bound to logical path BasicFacts`.

The BasicFacts.v is placed in the same folder to mine file.
What can I do about it?
All related files are compiled and able to be executed with Proof General/ CoqIDE

**Comment by ejgallego** [comment]
Hi @ASamSam , I think your problem is due to `coq-lsp` usually requiring a `_CoqProject` file in order to work.

Next version will include a more informative panel about it.

So for a simple project where all files are in the dir, you put in `_CoqProject`:
```
-R . MyLib
```
and ensure to do "open folder" in code of that folder.

You can see information about the detected paths in the Output -> coq lsp server events window.

**Comment by ASamSam** [comment]
Thank you very much. After constructing the Coq project, everything starts to work.
